In [0]:
import pandas as pd

In [0]:
data = pd.read_csv('skills.csv', index_col=0)

In [93]:
data = data.sort_values('count')
data = data.reset_index(drop=True)
data

                  skill  count
0     financial support      1
1                  qsar      1
2        fingerprinting      1
3       cheminformatics      1
4                ubuntu      1
...                 ...    ...
3998           software    839
3999         management   1032
4000              other   1422
4001             skills   1666
4002               data   5408

[4003 rows x 2 columns]

In [0]:
courses = pd.read_excel('courses.xlsx', index_col=0)
courses.columns = ['courses name', 'topic', 'prer']
courses = courses.reset_index()
courses.drop(columns='index', inplace=True)
courses.drop(columns='prer', inplace=True)

In [95]:
def remove(shit):
  if 'Game-playing AI with Swift for TensorFlow' in shit:
    return 'Game-playing AI with Swift for TensorFlow'
  else:
    return shit
courses['courses name'] = courses['courses name'].apply(remove)
courses['courses name'].value_counts()

Data Science Hands-on with Open Source Tools (Archived)    31
Data Science for Scala                                     25
Machine Learning with R                                    21
Data Science Tools                                         20
Deep Learning Fundamentals                                 19
Deep Learning with TensorFlow                              18
Digital Analytics & Regression                             17
Data Science with Open Data                                17
Big Data 101                                               16
Introduction to Data Science                               16
Machine Learning with Python                               15
Python for Data Science                                    15
Game-playing AI with Swift for TensorFlow                  13
Analyzing Big Data in R using Apache Spark                 12
Machine learning with Apache SystemML                      11
Data Science Methodology                                   10
Accelerating Deep Learning with GPU                        10
Spark MLlib                                                 8
Machine Learning – Dimensionality Reduction                 6
Name: courses name, dtype: int64

Convert to lower case

In [0]:
def toLower(shit):
  return shit.lower()

courses['courses name'] = courses['courses name'].apply(toLower)
courses['topic'] = courses['topic'].apply(toLower)

Search in course names

In [107]:
result = []
for i in range(len(data['skill'])):
  try:
    result += list(set(courses[courses['courses name'].str.contains(data['skill'][i])]['courses name']))*i
  except:
    pass

/usr/local/lib/python3.6/dist-packages/pandas/core/strings.py:1843: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

In [0]:
from collections import Counter
fuck = pd.Series(Counter(result))

In [0]:
fuck = pd.DataFrame(fuck)
fuck = fuck.reset_index()

In [114]:
fuck.columns = ['course name', 'score']
fuck = fuck.sort_values('score', ascending=False)
fuck

                                          course name  score
15              machine learning with apache systemml  39658
13         analyzing big data in r using apache spark  33554
9   data science hands-on with open source tools (...  32931
18                       machine learning with python  32739
2         machine learning – dimensionality reduction  32519
4                      digital analytics & regression  31641
17                            machine learning with r  28771
7                             python for data science  25739
11                             data science for scala  25133
8                         data science with open data  24206
6                       deep learning with tensorflow  23294
1                 accelerating deep learning with gpu  23264
3                        introduction to data science  22870
5                          deep learning fundamentals  19329
10                                 data science tools  17976
12                           data science methodology  17976
16                                        spark mllib  17322
0           game-playing ai with swift for tensorflow  14289
14                                       big data 101  10722

In [116]:
courses

                     courses name                                           topic
0    machine learning with python             supervised vs unsupervised learning
1    machine learning with python  python libraries suitable for machine learning
2    machine learning with python                               linear regression
3    machine learning with python                           non-linear regression
4    machine learning with python                        model evaluation methods
..                            ...                                             ...
295                  big data 101             the enhanced 360 view of a customer
296                  big data 101                       security and intelligence
297                  big data 101                             operations analysis
298                  big data 101                          ecosystems of big data
299                  big data 101                            the hadoop framework

[300 rows x 2 columns]

Search in the topics covered

In [118]:
result = []
for i in range(len(data['skill'])):
  try:
    result += list(set(courses[courses['topic'].str.contains(data['skill'][i])]['courses name']))*i
  except:
    pass
fuck = pd.Series(Counter(result))
fuck = pd.DataFrame(fuck)
fuck = fuck.reset_index()
fuck.columns = ['course name', 'score']
fuck = fuck.sort_values('score', ascending=False)
fuck

/usr/local/lib/python3.6/dist-packages/pandas/core/strings.py:1843: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

                                          course name   score
9                              data science for scala  122027
2                             machine learning with r   97777
10                                        spark mllib   95916
5                         data science with open data   90838
13                                       big data 101   84703
6   data science hands-on with open source tools (...   80504
12                       machine learning with python   78167
4                      digital analytics & regression   77725
17                       introduction to data science   76622
11                      deep learning with tensorflow   69265
18                                 data science tools   68922
1               machine learning with apache systemml   66889
0           game-playing ai with swift for tensorflow   61957
7                 accelerating deep learning with gpu   57584
3                          deep learning fundamentals   57448
8          analyzing big data in r using apache spark   54414
14                            python for data science   52471
16                           data science methodology   42252
15        machine learning – dimensionality reduction   31921